[package]
name = "mig"
version = "0.1.0"
authors = ["ogata-k <ogtkzk712@gmail.com>"]
description = "This application is converter from mig-file to migration-file of web framework."
edition = "2018"

[dependencies]
clap = "2.33"
chrono = "0.4.6"
failure = "0.1.5"
